let token=null,currentTab="news",editingId=null;
const tableFields={
news:[["title","Title"],["body","Body"],["date","Label / Date"]],
events:[["title","Title"],["description","Description"],["date","Date"]],
courses:[["title","Course Title"],["description","Description"]],
leadership:[["name","Name / Office"],["role","Role"],["bio","Bio"]],
units:[["name","Unit / Department"],["bio","Description"]],
downloads:[["title","Document Title"],["description","Description"],["url","File URL"]],
gallery:[["caption","Caption"],["image_url","Image URL"]]
};
const demo={news:[{id:1,title:"National Headquarters Announcements",body:"Official notices and updates.",date:"Official Update"}],events:[],courses:[],leadership:[],units:[],downloads:[],gallery:[]};
function configured(){return window.SUPABASE_URL&&window.SUPABASE_ANON_KEY}
function headers(){return {apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${token||SUPABASE_ANON_KEY}`,"Content-Type":"application/json"}}
async function api(path,opts={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...opts,headers:{...headers(),...(opts.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
document.getElementById("connection").innerHTML=configured()?'<span class="ok">Configuration found.</span>':'<span class="error">Supabase configuration is not set yet.</span>';
document.getElementById("login").onsubmit=async e=>{e.preventDefault();const msg=document.getElementById("auth-msg");if(!configured()){msg.textContent="Add your Supabase URL and anon/publishable key to config.js first.";msg.className="error";return}try{const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:SUPABASE_ANON_KEY,"Content-Type":"application/json"},body:JSON.stringify({email:email.value,password:password.value})});const d=await r.json();if(!r.ok)throw Error(d.msg||d.error_description||"Sign-in failed");token=d.access_token;document.getElementById("auth-panel").classList.add("hidden");document.getElementById("dashboard").classList.remove("hidden");openTab("news")}catch(err){msg.textContent=err.message;msg.className="error"}};
document.getElementById("logout").onclick=()=>location.reload();
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>openTab(b.dataset.tab));
async function openTab(tab){currentTab=tab;editingId=null;document.querySelectorAll(".tabs button").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));if(tab==="contact")return contactEditor();if(tab==="applications")return applicationsEditor();renderManager(tab)}
async function getRows(tab){try{return await api(`${tab}?select=*&order=created_at.desc`)}catch(e){return demo[tab]||[]}}
async function renderManager(tab){const m=document.getElementById("manager");const rows=await getRows(tab);m.innerHTML=`<div class="form-actions"><button onclick="showForm()">+ Add New</button><button class="secondary" onclick="renderManager('${tab}')">Refresh</button></div><div id="form-area"></div><div id="rows">${rows.length?rows.map(rowHtml).join(""):'<div class="empty">No items yet.</div>'}</div>`}
function rowHtml(r){const title=r.title||r.name||r.caption||"Untitled";return `<div class="item"><div><b>${escapeHtml(title)}</b><div class="small">${escapeHtml(r.date||r.role||r.description||r.body||"")}</div></div><div class="item-actions"><button onclick='editItem(${JSON.stringify(r).replace(/'/g,"&#39;")})'>Edit</button><button class="danger" onclick="deleteItem('${r.id}')">Delete</button></div></div>`}
function showForm(row={}){const area=document.getElementById("form-area");area.innerHTML=`<form id="edit-form" class="panel">${tableFields[currentTab].map(([key,label])=>`<label><b>${label}</b><input name="${key}" value="${escapeAttr(row[key]||"")}" ${key==="url"||key==="image_url"?"type=\"url\"":""}></label>`).join("")}<div class="form-actions"><button>Save</button><button type="button" class="secondary" onclick="renderManager('${currentTab}')">Cancel</button></div><p id="save-msg"></p></form>`;document.getElementById("edit-form").onsubmit=e=>saveItem(e,row.id)}
function editItem(row){showForm(row);window.scrollTo({top:0,behavior:"smooth"})}
async function saveItem(e,id){e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{if(!configured())throw Error("Connect Supabase first.");if(id)await api(`${currentTab}?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify(data)});else await api(currentTab,{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify(data)});renderManager(currentTab)}catch(err){document.getElementById("save-msg").textContent=err.message;document.getElementById("save-msg").className="error"}}
async function deleteItem(id){if(!confirm("Delete this item?"))return;try{await api(`${currentTab}?id=eq.${encodeURIComponent(id)}`,{method:"DELETE"});renderManager(currentTab)}catch(e){alert(e.message)}}
async function contactEditor(){const m=document.getElementById("manager");let c={};try{const rows=await api("site_settings?select=*");c=Object.fromEntries(rows.map(x=>[x.key,x.value]))}catch(e){}const keys=["email","phone","address","facebook","instagram","whatsapp","youtube"];m.innerHTML=`<form class="panel" id="contact-form"><h3>Contact & Social Links</h3>${keys.map(k=>`<label><b>${k}</b><input name="${k}" value="${escapeAttr(c[k]||"")}"></label>`).join("")}<button>Save Contact Settings</button><p id="contact-msg"></p></form>`;document.getElementById("contact-form").onsubmit=async e=>{e.preventDefault();try{for(const [key,value] of Object.entries(Object.fromEntries(new FormData(e.target))))await api(`site_settings?key=eq.${encodeURIComponent(key)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({value})});document.getElementById("contact-msg").textContent="Saved.";document.getElementById("contact-msg").className="ok"}catch(err){document.getElementById("contact-msg").textContent=err.message;document.getElementById("contact-msg").className="error"}}}
async function applicationsEditor(){const m=document.getElementById("manager");try{const rows=await api("membership_applications?select=*&order=created_at.desc");m.innerHTML=rows.length?rows.map(r=>`<div class="item"><div><b>${escapeHtml(r.full_name)}</b><div class="small">${escapeHtml(r.email)} · ${escapeHtml(r.phone||"")} · ${escapeHtml(r.category||"")} · ${escapeHtml(r.state_command||"")}</div></div><span class="badge">${escapeHtml(r.status||"New")}</span></div>`).join(""):'<div class="empty">No applications yet.</div>'}catch(e){m.innerHTML=`<p class="error">${escapeHtml(e.message)}</p>`}}
function escapeHtml(v=""){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function escapeAttr(v=""){return escapeHtml(v).replace(/`/g,"&#96;")}
