-- AH-LDI / Civil Guards Nigeria free CMS schema for Supabase
-- Run this in Supabase SQL Editor.
-- Then create an admin user in Authentication > Users.

create table if not exists leadership (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  bio text,
  created_at timestamptz default now()
);
create table if not exists units (
  id bigint generated by default as identity primary key,
  name text not null,
  bio text,
  created_at timestamptz default now()
);
create table if not exists courses (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  created_at timestamptz default now()
);
create table if not exists news (
  id bigint generated by default as identity primary key,
  title text not null,
  body text,
  date text,
  created_at timestamptz default now()
);
create table if not exists events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  date text,
  created_at timestamptz default now()
);
create table if not exists downloads (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  url text,
  created_at timestamptz default now()
);
create table if not exists gallery (
  id bigint generated by default as identity primary key,
  caption text,
  image_url text,
  created_at timestamptz default now()
);
create table if not exists site_settings (
  key text primary key,
  value text default ''
);
create table if not exists membership_applications (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text,
  category text,
  state_command text,
  status text default 'New',
  created_at timestamptz default now()
);

-- Public read access for published website content.
alter table leadership enable row level security;
alter table units enable row level security;
alter table courses enable row level security;
alter table news enable row level security;
alter table events enable row level security;
alter table downloads enable row level security;
alter table gallery enable row level security;
alter table site_settings enable row level security;
alter table membership_applications enable row level security;

create policy "public read leadership" on leadership for select using (true);
create policy "public read units" on units for select using (true);
create policy "public read courses" on courses for select using (true);
create policy "public read news" on news for select using (true);
create policy "public read events" on events for select using (true);
create policy "public read downloads" on downloads for select using (true);
create policy "public read gallery" on gallery for select using (true);
create policy "public read settings" on site_settings for select using (true);

-- Anyone can submit a membership application; only authenticated admins should read/manage applications.
create policy "public submit membership" on membership_applications for insert with check (true);
create policy "authenticated read membership" on membership_applications for select to authenticated using (true);
create policy "authenticated manage membership" on membership_applications for all to authenticated using (true) with check (true);

-- Authenticated admin users can manage all CMS tables.
create policy "authenticated manage leadership" on leadership for all to authenticated using (true) with check (true);
create policy "authenticated manage units" on units for all to authenticated using (true) with check (true);
create policy "authenticated manage courses" on courses for all to authenticated using (true) with check (true);
create policy "authenticated manage news" on news for all to authenticated using (true) with check (true);
create policy "authenticated manage events" on events for all to authenticated using (true) with check (true);
create policy "authenticated manage downloads" on downloads for all to authenticated using (true) with check (true);
create policy "authenticated manage gallery" on gallery for all to authenticated using (true) with check (true);
create policy "authenticated manage settings" on site_settings for all to authenticated using (true) with check (true);
